<template>
  <div class="loading-overlay">
    <div class="loading-icon loadingio-spinner-dual-ball-diygtahw77l">
      <div class="ldio-ivrah2ubap">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.loading-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: 9999;
}

.loading-icon {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

@keyframes ldio-ivrah2ubap-o {
  0% {
    opacity: 1;
    transform: translate(0 0);
  }
  49.99% {
    opacity: 1;
    transform: translate(80px, 0);
  }
  50% {
    opacity: 0;
    transform: translate(80px, 0);
  }
  100% {
    opacity: 0;
    transform: translate(0, 0);
  }
}
@keyframes ldio-ivrah2ubap {
  0% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(80px, 0);
  }
  100% {
    transform: translate(0, 0);
  }
}
.ldio-ivrah2ubap div {
  position: absolute;
  width: 80px;
  height: 80px;
  border-radius: 50%;
  top: 60px;
  left: 20px;
}
.ldio-ivrah2ubap div:nth-child(1) {
  background: #804d1e;
  animation: ldio-ivrah2ubap 2.5s linear infinite;
  animation-delay: -1.25s;
}
.ldio-ivrah2ubap div:nth-child(2) {
  background: #f2edde;
  animation: ldio-ivrah2ubap 2.5s linear infinite;
  animation-delay: 0s;
}
.ldio-ivrah2ubap div:nth-child(3) {
  background: #804d1e;
  animation: ldio-ivrah2ubap-o 2.5s linear infinite;
  animation-delay: -1.25s;
}
.loadingio-spinner-dual-ball-diygtahw77l {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-ivrah2ubap {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ivrah2ubap div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
